name: Reboot Instance Daily

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * *'

jobs:
  reboot:
    runs-on: ubuntu-latest
    steps:
      - uses: saml-to/assume-aws-role-action@main
        with:
          role: arn:aws:iam::656661431918:role/rebooter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: aws ec2 reboot-instances --instance-ids i-09313277b1ba99c83
